---
title: "Before you submit your Package"
---

Read here about our Data and Code Availability Policy and make sure you comply with all requirements before you submit the paper for the first time. Check the cases in which exemptions to the policy can be granted and the procedures to obtain them. If you don't request the exemption at the time of first submission, you will not be able to do it later! Also, there may still be time to gain some insights from our [best practice for reproducibility recommendations](best.qmd) before you submit.


## Data and Code Availability Policy

:::{.callout-note}

# Official Policy at JPE

This is a reproduction of the official Data and Code Availability Policy of the JPE, which can be found [here](https://www.journals.uchicago.edu/journals/jpe/datapolicy). In case of discrepancy, the official policy always prevails to the reproduction presented here.
:::

The JPE requires authors of empirical, experimental or numerical papers to provide documentation of how their results were obtained in sufficient detail and accuracy to allow their results to be replicated. When you submit a paper for consideration, you will be asked to confirm that you are willing to comply with this policy. **It is essential that you request a data exemption at the point of first submission if you face any restrictions that prevent you from publishing your data or, in general, from complying with any of the provisions of this policy.** More details on this process are provided below.

::: {.callout-important}
# When Will my Paper be Accepted for Publication?

Your paper will be accepted for final publication **only after the results have been checked for reproducibility**. 
:::

Our mission is to conduct the reproducibility checks as fast as possible. Please read the information on this website carefully, so we can achieve this goal. Please, also note the following warning:

::: {.callout-warning}
The editorial board of the JPE reserves the right to refuse publication of papers whose authors do not comply with the requirements set out in detail below for each type of paper.
:::

Once the paper is accepted for publication, the replication package will be posted on the journal's repository at [dataverse.edu](https://dataverse.harvard.edu/dataverse/JPE) and it will be linked with the paper.  Submission on this online repository indicates that the authors license users to download, copy, and modify this material. Users of the material must acknowledge all authors as the original creators and cite both the replication package and the paper accordingly.

::: {.callout-tip}

# Instructions for Replication Package

Please follow precise instructions on how to structure your replication package [here](package.qmd).

:::


## Apply to exemptions to the Data and Code Availability Policy {#sec-apply-exemption}

If you are not able to comply with some of the aspects of the Data and Code Availability Policy (e.g. because you are using restricted-access data or you cannot obtain permission to re-publish the data), you should request an exemption **at the time of first submission of your paper**. You can find a set of Frequently Asked Questions about the situations under which you can or cannot apply to an exemption to the data and code availability policy [here](faqs.qmd). 

If you want to request a Data Exemption, *here is what you need to do*

Additionally, attach a Cover Letter along with your paper in which you indicate the reasons why you believe you are entitled to an exemption to our data and code availability policy. 

Once the paper is submitted, the Managing Editor will analyze whether (i) there are enough grounds to grant the exemption and (ii) the exemption or the nature of the data limits the interest of the paper. Based on their assessment of these two points, they will make one of the following decisions: (a) move forward with the process, sending your paper to referees, (b) summarily reject your paper, or (c) contact you, asking to provide additional information, documentation, or any other requirement that they need to assess the suitability of the requested exemption. The exemptions are tacitly granted by choosing option (a). 

Once your paper is conditionally accepted, you will be requested to supply your replication package according to the guidelines specified [here on this website](package.qmd). If an exemption to the Data and Code Availability Policy was granted, you will be requested to either provide the Data Editor (and, by extension, the team of replicators) with temporary access to the data affected by the exemption for the sole purpose of implementing the reproducibility checks. Alternatively, when granting temporary access to the restricted data is not possible, you will be required to include in your package a synthetic or simulated dataset that allows users to run the code and check that it produces all outputs from the paper (and appendices), even if the results do not match those in the paper. This is all laid out in detail in the [JPE Data and Code Policy](policy.qmd). You can find a set of FAQs questions about how to proceed with the replication package when an exemption to the Data and Code Availability Policy has been granted [here](faqs#procedures-when-exemptions-are-granted). 