---
format:
    pdf: default
---


The replication package is deposited under DOI `xyz`.

Code | Meaning | Data Statement
:-:|:--:| :-------
A    | Available | Data and code for this paper are available in the above deposit. They were checked by the Journal for their ability to reproduce the results presented in the paper.
S    | Simulation  |  The authors were granted an exemption to publish their data because access is restricted. However, the authors provided a simulated or synthetic dataset that allowed the Journal to run their code. The synthetic/simulated data and code are available in the above deposit. They were checked for their ability to generate all tables and figures in the paper. However, the synthetic/simulated data are not designed to reproduce the same results.
T    | Temporary | The authors were granted an exemption to publish their data because access is restricted. However, the authors provided the Journal with temporary access to the data, which allowed the Journal to run their code. Code and unrestricted data are available in the above deposit. Data and code were checked by the Journal for their ability to reproduce the results presented in the paper.
P1   | Partial 1 | Given the highly demanding nature of the algorithms, the reproducibility checks were run on a simplified version of the code, which is also available in the deposit. [which is to be added right after the end of any of the previous three statements].
P2   | Partial 2 | Given the highly demanding nature of the algorithms, the reproducibility checks were performed on a subset or results only. Those are clearly indicated in the accompanying README file of the replication package. [which is to be added right after the end of any of the previous three statements].
A;T  | Available, Temporary | Data and code for this paper are available in the above deposit. They were checked by the Journal for their ability to reproduce the results presented in the paper. The authors were granted an exemption to publish parts of their data because access to these data is restricted. However, the authors provided the Journal with temporary access to the data, which enabled the Journal to check reproducibility of results. Code for all parts of the paper and unrestricted data are available in the above deposit.
A;S  | Available, Simulation | Data and code for this paper are available in the above deposit. They were checked by the Journal for their ability to reproduce the results presented in the paper. The authors were granted an exemption to publish parts of their data because access to these data is restricted. However, the authors provided the Journal provided a simulated or synthetic dataset, which enabled the Journal to run the code. Code for all parts of the paper and unrestricted data are available in the above deposit. They were checked for their ability to generate all tables and figures in the paper, however the synthetic/simulated data are not designed to reproduce the same results.
A;T;S  | Available, Temporary, Simulation | Data and code for this paper are available in the above deposit. They were checked by the Journal for their ability to reproduce the results presented in the paper. The authors were granted an exemption to publish parts of their data because access to these data is restricted. However, the authors provided the Journal with temporary access to the parts of the restricted data, which enabled the Journal to check reproducibility of results. Other parts of the data remained inaccessibel to the Journal, and the authors provided a simulated or synthetic dataset, which enabled the Journal to run the code. Code for all parts of the paper and unrestricted data are available in the above deposit. They were checked for their ability to generate all tables and figures in the paper, however the synthetic/simulated data are not designed to reproduce the same results.

: {tbl-colwidths="[5,15,80]"}